# Always find expect() first; further modules may use as a 'builtin' i.e. without include()
include(Expect)

include(AddGoogleExecutable)
include(AddLocalAllTarget)
include(AlignStrings)
include(ConfigureRPathVariables)
include(FileToRawStringLiteral)
include(HelpParseArguments)
include(HighlightTargetOutput)
include(LogVars)
include(MessageGate)
include(ProjectDllExport)
include(RecordAliasDefinitions)
include(SetupBuildMode)
include(SortListByLength)
include(StringCapitalize)
include(TargetUtilities)
