# Always find expect() first; further modules may use as a 'builtin' i.e. without find_package()
find_package(Expect CONFIG REQUIRED)

find_package(AddGoogleExecutable CONFIG REQUIRED)
find_package(AddLocalAllTarget CONFIG REQUIRED)
find_package(AlignStrings CONFIG REQUIRED)
find_package(ConfigureRPathVariables CONFIG REQUIRED)
find_package(FileToRawStringLiteral CONFIG REQUIRED)
find_package(HelpParseArguments CONFIG REQUIRED)
find_package(HighlightTargetOutput CONFIG REQUIRED)
find_package(LogVars CONFIG REQUIRED)
find_package(MessageGate CONFIG REQUIRED)
find_package(ProjectDllExport CONFIG REQUIRED)
find_package(SetupBuildMode CONFIG REQUIRED)
find_package(StringCapitalize CONFIG REQUIRED)
find_package(TargetUtilities CONFIG REQUIRED)
